const EVENT_TYPE_TIME_SPAN_CHANGE = 'EVENT_TYPE_TIME_SPAN_CHANGE';
const EVENT_TYPE_BOTTOM_TAB_CHANGE = 'EVENT_TYPE_BOTTOM_TAB_CHANGE';
const EVENT_TYPE_HOT_FAVORITE_CHANGE = 'EVENT_TYPE_HOT_FAVORITE_CHANGE';
const EVENT_TYPE_TRENDING_FAVORITE_CHANGE = 'EVENT_TYPE_TRENDING_FAVORITE_CHANGE';

export {
    EVENT_TYPE_TIME_SPAN_CHANGE,
    EVENT_TYPE_BOTTOM_TAB_CHANGE,
    EVENT_TYPE_HOT_FAVORITE_CHANGE,
    EVENT_TYPE_TRENDING_FAVORITE_CHANGE,
};
