export default {
    // == 主题
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    SHOW_THEME_VIEW: "SHOW_THEME_VIEW",
    // == 最热
    HOT_REFRESH: 'HOT_REFRESH',
    HOT_REFRESH_SUCCESS: 'HOT_REFRESH_SUCCESS',
    HOT_REFRESH_FAIL: 'HOT_REFRESH_FAIL',
    HOT_LOAD_MORE: 'HOT_LOAD_MORE',
    HOT_LOAD_MORE_SUCCESS: 'HOT_LOAD_MORE_SUCCESS',
    // == 趋势
    TRENDING_REFRESH: 'TRENDING_REFRESH',
    TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
    TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
    TRENDING_LOAD_MORE: 'TRENDING_LOAD_MORE',
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
    // == 收藏
    FAVORITE_REFRESH: 'FAVORITE_REFRESH',
    FAVORITE_REFRESH_SUCCESS: 'FAVORITE_REFRESH_SUCCESS',
    FAVORITE_REFRESH_FAIL: 'FAVORITE_REFRESH_FAIL',
    FAVORITE_LOAD_MORE: 'FAVORITE_LOAD_MORE',
    FAVORITE_LOAD_MORE_SUCCESS: 'FAVORITE_LOAD_MORE_SUCCESS',
    // == 最热和趋势模块自定义标签
    LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
    // == 搜索
    SEARCH_REFRESH: "SEARCH_REFRESH",// 搜索
    SEARCH_REFRESH_SUCCESS: "SEARCH_REFRESH_SUCCESS",
    SEARCH_REFRESH_FAIL: "SEARCH_REFRESH_FAIL", 
    SEARCH_LOAD_MORE: "SEARCH_LOAD_MORE",// 上拉
    SEARCH_LOAD_MORE_SUCCESS: "SEARCH_LOAD_MORE_SUCCESS",
    SEARCH_CANCEL: "SEARCH_CANCEL", // 取消
};
