export default {
    THEME_CHANGE: 'THEME_CHANGE',
    // == 最热
    HOT_REFRESH: 'HOT_REFRESH',
    HOT_REFRESH_SUCCESS: 'HOT_REFRESH_SUCCESS',
    HOT_REFRESH_FAIL: 'HOT_REFRESH_FAIL',
    HOT_LOAD_MORE: 'HOT_LOAD_MORE',
    HOT_LOAD_MORE_SUCCESS: 'HOT_LOAD_MORE_SUCCESS',
    // == 趋势
    TRENDING_REFRESH: 'TRENDING_REFRESH',
    TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
    TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
    TRENDING_LOAD_MORE: 'TRENDING_LOAD_MORE',
    TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
};
