export default {
    THEME_CHANGE: 'THEME_CHANGE',
    HOT_REFRESH: 'HOT_REFRESH',
    HOT_REFRESH_SUCCESS: 'HOT_REFRESH_SUCCESS',
    HOT_REFRESH_FAIL: 'HOT_REFRESH_FAIL',
    HOT_LOAD_MORE: 'HOT_LOAD_MORE',
    HOT_LOAD_MORE_SUCCESS: 'HOT_LOAD_MORE_SUCCESS',
};
